##Hi, As given in the example te functions below work exactly same way
##makeCacheMatrix() creates a list of 4 functions, set and get matrix value
##and setInv, getInv, which stores inverted matrix

##Next comes cacheSolve() function, which takes a list of 4 functions generated by
##makeCacheMatrix as input and checks if the inverted value is in cache or not
##if it is there then returns cached value otherwise call solve() method to
##calculate inverse and then cached it

##There is another function called inverse() which is there only to take matrix to
##be inverted as input then calls makeCacheMatrix() to make a chached matrix with
##input as data. Then solveCache() is called having argument as cached matrix
## Write a short comment describing this function

##Makes a list of 4 functions, caches matrix, stores its inverse, and returns
##matrix or its inverse whenever appropriate function is called upon
makeCacheMatrix <- function(x = matrix()) {
  inv <- NULL
  set <- function(y) {
    x <<- y
    inv <<- NULL
  }
  get <- function() x
  setInv <- function(Inv) inv <<- Inv
  getInv <- function() inv
  list(set = set, get = get,
       setInv = setInv,
       getInv = getInv)

}

##Takes input argment as output of makeCacheMatrix() and check if this input has
##Inverse stored in it,if yes then return that value , else uses 'R' inbuilt
##method solve() to calculate inverse, caches it, and return Inverse
cacheSolve <- function(x = makeCacheMatrix(), ...) {
  ## Return a matrix that is the inverse of 'x
  Inv <- x$getInv()
  if(!is.null(Inv) && is.matrix(Inv)){
    message("getting cached Inverse")
    return(Inv)
  }
  mat <- x$get()
  if(det(mat) == 0) return("Non-Invertible Matrix")
  Inv <- solve(mat)
  x$setInv(Inv)
  Inv
}

##To test this R script,just call inverse function with a square matrix as
##as its argument e.g write in console inverse(matrix(c(1:8,12),3,3)) 

inverse <- function(x){
  cacheSolve(makeCacheMatrix(x))
}